'''
Configuration files used by the other modules
'''


AUTOPLAY = False
SERVER_IP = '127.0.0.1'
MOVE_TIMEOUT = 60
MOVE_TIME_OVERHEAD = 10
DEBUG = False
WHITE_SERVER_PORT = 5800
BLACK_SERVER_PORT = 5801
PLAYER_SERVER_PORT = WHITE_SERVER_PORT
WHITE_ROLE = 'White'
BLACK_ROLE = 'Black'
PLAYER_ROLE = WHITE_ROLE
PLAYER_NAME = 'CalbiFalai'
BOARD_SIZE = 9
