'''
Configuration files used by the other modules
'''


# Flags
AUTOPLAY = False
DEBUG = False
TRAIN = False

# Players
MY_PLAYER = None
WHITE_PLAYER = None
BLACK_PLAYER = None

# Server configs
SERVER_IP = '127.0.0.1'
WHITE_SERVER_PORT = 5800
BLACK_SERVER_PORT = 5801
PLAYER_SERVER_PORT = WHITE_SERVER_PORT
PLAYER_NAME = 'CalbiFalai'

# Generic configs
GIVEN_MOVE_TIMEOUT = 60.0
MOVE_TIME_OVERHEAD = 4.0
MOVE_TIMEOUT = GIVEN_MOVE_TIMEOUT - MOVE_TIME_OVERHEAD

# Roles
WHITE_ROLE = 'White'
BLACK_ROLE = 'Black'
PLAYER_ROLE = WHITE_ROLE

# Board configs
BOARD_SIZE = 9

# Genetic configs
GEN_GENERATIONS = 10
GEN_POPULATION = 10
